version: '3.1'

services:
  php:
    container_name: ${APP_NAME}-php
    image: laric/php
    restart: always
    links:
      - postgres
    volumes:
      - ./:/app

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    restart: always
    links:
      - php
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./:/app
      - ./docker/nginx-conf:/etc/nginx/conf.d
      - ./docker/certs:/etc/nginx/certs

  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres
    restart: always
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data

  redis:
    container_name: ${APP_NAME}-redis
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command:
      - redis-server
      - --port ${REDIS_PORT}
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis-data:/data
